# Generated by Django 5.1.3 on 2024-11-07 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvallevel',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approvals.approver'),
        ),
    ]
